import type { Metadata } from 'next';
import './globals.css';
import { CommonRootLayout, ICommonRootLayout } from '#packages-common-lib';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menus: ICommonRootLayout.MenuItem[] = [{ name: '/test/basic', href: '/test/basic' }];
  return (
    <html lang="ko">
      <body>
        <CommonRootLayout menus={menus}>{children}</CommonRootLayout>
      </body>
    </html>
  );
}
