import type { Metadata } from 'next';
import './globals.css';
import { CommonRootLayout, ICommonRootLayout } from '#packages-common-lib';
import { RootLayoutClient } from './layout.client';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menus: ICommonRootLayout.MenuItem[] = [
    { name: '/test/basic', href: '/test/basic' },
    { name: '/test/other-page-1', href: '/test/other-page-1' },
    { name: '/test/other-page-2', href: '/test/other-page-2' },
  ];

  return (
    <html lang="ko">
      <body>
        <CommonRootLayout menus={menus}>
          <RootLayoutClient>{children}</RootLayoutClient>
        </CommonRootLayout>
      </body>
    </html>
  );
}
