import type { Metadata } from 'next';
import './globals.css';
import { CommonRootLayout, ICommonRootLayout } from '#packages-common-lib';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menus: ICommonRootLayout.MenuItem[] = [
    { name: '/test/date-valid-check', href: '/test/date-valid-check' },
    { name: '/test/datetime-valid-check', href: '/test/datetime-valid-check' },
    { name: '/test/email-valid-check', href: '/test/email-valid-check' },
    { name: '/test/time-valid-check', href: '/test/time-valid-check' },
  ];

  return (
    <html lang="ko">
      <body>
        <CommonRootLayout menus={menus}>{children}</CommonRootLayout>
      </body>
    </html>
  );
}
