import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';
import { CommonRootLayout, ICommonRootLayout } from '#packages-common-lib';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menus: ICommonRootLayout.MenuItem[] = [{ name: '/test/button', href: '/test/button' }];

  return (
    <html lang="ko">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <CommonRootLayout menus={menus}>{children}</CommonRootLayout>
      </body>
    </html>
  );
}
