name: github-action-ubuntu-test

on:
  push:
    tags:
      - 'github-action-ubuntu-test-v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'

jobs:
  publish-release-registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update -y
      # - run: sudo apt-get upgrade -y
      - run: sudo apt-get install -y pkg-config wget gcc make
      - run: wget https://github.com/openssl/openssl/releases/download/openssl-3.3.2/openssl-3.3.2.tar.gz
      - run: tar -xvf openssl-3.3.2.tar.gz
      - run: cd openssl-3.3.2 && ./config && make && make install
      - run: openssl version
      - run: openssl version -d
